
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://maven.zohodl.com/"}
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://maven.zohodl.com/"}
    }
}
include ':app'
rootProject.name='Assist-Customer-Android-SDK-demo'
